### ISSUE TITLE
Collect VEP output from worker nodes, upload to HDFS

### ISSUE THREAD

**Issue by toanddt** [variant-annotation/vep-spark#3]
- Collect VEP outputs (annotation information, stat information)
- Merge and sort the output
- Upload output to HDFS

**Comment by toanddt** [comment]
@nguyenthucquanghung. Please create pull request so that we can close this issue

**Comment by toanddt** [comment]
Can you use copyMerge from org.apache.hadoop.fs.FileUtil?

**Comment by nguyenthucquanghung** [comment]
The copyMerge function from org.apache.hadoop.fs.FileUtil is deprecated from hadoop version 3 and above. Hence I prefer to manually implement it.
